// RAP commitments seeded from Canadian companies' OWN PUBLIC disclosures
// (reconciliation / ESG / sustainability reports). Each carries a `source`.
//
// Data-integrity rules for this seed:
//  • These are the companies' *public commitments* — NOT sensitive Indigenous
//    data (which stays with communities / the client). See data-sovereignty note.
//  • Status never exceeds `reported` (self-reported). Nothing is `confirmed`,
//    because supplier/Nation confirmation is exactly the layer the portal adds
//    and that we do not have for scraped public data.
//  • rapType (Australian RAP tiers) is omitted — these are Canadian orgs
//    (CCAB/CCIB PAIR, TRC Call to Action #92), a different maturity framework.
//  • Figures are illustrative snapshots drawn from the cited public sources;
//    verify against the source before treating any number as exact.
import type {
  Commitment,
  CommitmentType,
  OrgSize,
  ProgressPoint,
  RapType,
  Sector,
} from "./types";

const T = "2025-01-15T00:00:00.000Z";

// Build a Commitment with an explicit, fixed field order. The DynamoDB
// round-trip (itemToCommitment) reconstructs in this SAME order, so the
// dynamo ≡ mock JSON equality in verify.ts holds. current status/% = last point.
function mk(p: {
  id: string;
  orgName: string;
  orgId?: string;
  sector: Sector;
  orgSize: OrgSize;
  type: CommitmentType;
  title: string;
  targetYear: number;
  rapType?: RapType;
  history: ProgressPoint[];
  source?: { label: string; url: string };
  detail?: string;
  targetText?: string;
}): Commitment {
  const last = p.history[p.history.length - 1];
  return {
    id: p.id,
    orgName: p.orgName,
    ...(p.orgId !== undefined ? { orgId: p.orgId } : {}),
    sector: p.sector,
    orgSize: p.orgSize,
    type: p.type,
    title: p.title,
    targetYear: p.targetYear,
    ...(p.rapType !== undefined ? { rapType: p.rapType } : {}),
    status: last.status,
    progressPct: last.progressPct,
    history: p.history,
    createdAt: T,
    ...(p.source !== undefined ? { source: p.source } : {}),
    ...(p.detail !== undefined ? { detail: p.detail } : {}),
    ...(p.targetText !== undefined ? { targetText: p.targetText } : {}),
  };
}

const h = (period: string, status: ProgressPoint["status"], progressPct: number): ProgressPoint => ({
  period,
  status,
  progressPct,
});

// Sources (companies' own public reconciliation / ESG pages).
const SRC = {
  rbc: { label: "RBC Reconciliation Action Plan 2025–2027", url: "https://www.rbc.com/indigenous/reconciliation-action-plan.html" },
  bmo: { label: "BMO Indigenous Commitments", url: "https://www.bmo.com/en-ca/main/about-bmo/our-impact/communities/indigenous-commitments/" },
  scotia: { label: "Scotiabank Truth & Reconciliation Action Plan", url: "https://www.scotiabank.com/ca/en/about/responsibility-impact/truth-reconciliation.html" },
  td: { label: "TD and Indigenous Peoples", url: "https://www.td.com/ca/en/about-td/diversity-and-inclusion/indigenous-peoples" },
  cenovus: { label: "Cenovus Indigenous Reconciliation", url: "https://www.cenovus.com/Sustainability/Social/Indigenous-reconciliation" },
  suncor: { label: "Suncor — Journey of Reconciliation", url: "https://sustainability.suncor.com/en/communities/partnering-with-indigenous-businesses-and-communities" },
  hydroone: { label: "Hydro One Indigenous Procurement", url: "https://www.hydroone.com/about/suppliers/indigenous-procurement" },
  teck: { label: "Teck 2024 Sustainability Report", url: "https://www.teck.com/media/2024-Sustainability-Report.pdf" },
  vale: { label: "Vale (NL) — NRCan profile", url: "https://natural-resources.canada.ca/maps-tools-publications/publications/vale-inco-newfoundland-labrador" },
  cn: { label: "CN Indigenous Reconciliation Report 2025", url: "https://www.railway.supply/cn-releases-first-indigenous-reconciliation-report/" },
} as const;

export const commitmentFixtures: Commitment[] = [
  // ── Finance ──────────────────────────────────────────────────────────────
  mk({
    id: "cm-rbc-proc",
    orgName: "RBC (Royal Bank of Canada)",
    sector: "finance",
    orgSize: "enterprise",
    type: "procurement",
    title: "RAP 2025–2027: grow Indigenous procurement across five ambition areas",
    detail: "Under RBC's 2025 to 2027 Reconciliation Action Plan, grow procurement with Indigenous-owned suppliers across its five ambition areas.",
    targetText: "higher Indigenous supplier spend by 2027",
    targetYear: 2027,
    history: [h("2025", "committed", 15), h("2026", "in_progress", 35)],
    source: SRC.rbc,
  }),
  mk({
    id: "cm-rbc-emp",
    orgName: "RBC (Royal Bank of Canada)",
    sector: "finance",
    orgSize: "enterprise",
    type: "employment",
    title: "RAP 2025–2027: expand Indigenous recruitment & retention",
    detail: "Expand Indigenous recruitment, development and retention programs under the same Reconciliation Action Plan.",
    targetText: "grow Indigenous workforce representation",
    targetYear: 2027,
    history: [h("2025", "committed", 10), h("2026", "in_progress", 28)],
    source: SRC.rbc,
  }),
  mk({
    id: "cm-bmo-proc",
    orgName: "BMO (Bank of Montreal)",
    sector: "finance",
    orgSize: "enterprise",
    type: "procurement",
    title: "Spend $10M annually with Indigenous suppliers (exceeded, $125M cumulative)",
    detail: "An annual Indigenous procurement target BMO reports having exceeded, reaching roughly $125M cumulative spend.",
    targetText: "$10M per year (exceeded)",
    targetYear: 2023,
    history: [h("2021", "in_progress", 55), h("2022", "reported", 90), h("2023", "reported", 100)],
    source: SRC.bmo,
  }),
  mk({
    id: "cm-bmo-gov",
    orgName: "BMO (Bank of Montreal)",
    sector: "finance",
    orgSize: "enterprise",
    type: "governance",
    title: "Maintain Gold-level PAIR (CCIB) certification & Office of Reconciliation",
    detail: "Sustain CCIB Gold-level Partnership Accreditation in Indigenous Relations and run a dedicated Office of Reconciliation.",
    targetText: "Gold PAIR maintained",
    targetYear: 2025,
    history: [h("2023", "in_progress", 60), h("2025", "reported", 100)],
    source: SRC.bmo,
  }),
  mk({
    id: "cm-scotiabank-proc",
    orgName: "Scotiabank",
    sector: "finance",
    orgSize: "enterprise",
    type: "procurement",
    title: "Truth & Reconciliation Action Plan: increase Indigenous supplier procurement",
    detail: "Part of Scotiabank's Truth and Reconciliation Action Plan (37 commitments): grow spend with Indigenous suppliers.",
    targetText: "increase Indigenous procurement",
    targetYear: 2025,
    history: [h("2023", "committed", 20), h("2024", "in_progress", 45), h("2025", "in_progress", 62)],
    source: SRC.scotia,
  }),
  mk({
    id: "cm-td-rel",
    orgName: "TD Bank Group",
    sector: "finance",
    orgSize: "enterprise",
    type: "relationships",
    title: "Invest $25M+ in Indigenous education, housing & employment (since 2022)",
    detail: "Community investment across Indigenous education, housing and employment; TD reports over $25M granted since 2022.",
    targetText: "$25M+ community investment",
    targetYear: 2025,
    history: [h("2022", "in_progress", 40), h("2024", "reported", 78)],
    source: SRC.td,
  }),

  // ── Energy ───────────────────────────────────────────────────────────────
  mk({
    id: "cm-cenovus-proc",
    orgName: "Cenovus Energy",
    sector: "energy",
    orgSize: "enterprise",
    type: "procurement",
    title: "Spend a minimum $1.2B with Indigenous businesses (2019–2025)",
    detail: "Cenovus's cumulative Indigenous business spend target across the 2019 to 2025 period.",
    targetText: "$1.2B cumulative (2019 to 2025)",
    targetYear: 2025,
    history: [h("2021", "in_progress", 45), h("2023", "in_progress", 72), h("2025", "reported", 95)],
    source: SRC.cenovus,
  }),
  mk({
    id: "cm-suncor-proc",
    orgName: "Suncor Energy",
    sector: "energy",
    orgSize: "enterprise",
    type: "procurement",
    title: "Sustain ~20% of total spend (~$3B/yr) with Indigenous suppliers",
    detail: "Indigenous procurement embedded into operations at roughly 20% of total spend (about $3B per year).",
    targetText: "~20% of total spend",
    targetYear: 2024,
    history: [h("2022", "in_progress", 70), h("2023", "reported", 90), h("2024", "reported", 100)],
    source: SRC.suncor,
  }),
  mk({
    id: "cm-hydroone-proc",
    orgName: "Hydro One",
    sector: "energy",
    orgSize: "large",
    type: "procurement",
    title: "Allocate ≥5% of annual procurement to Indigenous suppliers",
    detail: "Hydro One's supplier-diversity target to direct a minimum share of annual procurement to Indigenous businesses.",
    targetText: "at least 5% of annual procurement",
    targetYear: 2025,
    history: [h("2021", "in_progress", 50), h("2023", "in_progress", 66)],
    source: SRC.hydroone,
  }),

  // ── Mining ───────────────────────────────────────────────────────────────
  mk({
    id: "cm-teck-emp",
    orgName: "Teck Resources",
    sector: "mining",
    orgSize: "enterprise",
    type: "employment",
    title: "Increase Indigenous employment representation by end 2025",
    detail: "Increase Indigenous representation across Teck's workforce by the end of 2025.",
    targetText: "higher Indigenous employment by 2025",
    targetYear: 2025,
    history: [h("2023", "committed", 25), h("2024", "in_progress", 48), h("2025", "in_progress", 60)],
    source: SRC.teck,
  }),
  mk({
    id: "cm-teck-rel",
    orgName: "Teck Resources",
    sector: "mining",
    orgSize: "enterprise",
    type: "relationships",
    title: "Contribute $100M to community organizations & initiatives by end 2025",
    detail: "A community contribution target to organizations and initiatives, including Indigenous communities, by end 2025.",
    targetText: "$100M to communities by 2025",
    targetYear: 2025,
    history: [h("2022", "in_progress", 55), h("2024", "reported", 82), h("2025", "reported", 96)],
    source: SRC.teck,
  }),
  mk({
    id: "cm-vale-emp",
    orgName: "Vale Canada",
    sector: "mining",
    orgSize: "enterprise",
    type: "employment",
    title: "Maximize Indigenous employment & business opportunities at Labrador operations",
    detail: "Maximize Indigenous employment and business opportunities at Vale's Labrador operations (Voisey's Bay, Long Harbour).",
    targetText: "Indigenous employment and business in Labrador",
    targetYear: 2025,
    history: [h("2023", "committed", 30), h("2024", "in_progress", 46)],
    source: SRC.vale,
  }),

  // ── Transport ────────────────────────────────────────────────────────────
  mk({
    id: "cm-cn-emp",
    orgName: "CN (Canadian National Railway)",
    sector: "transport",
    orgSize: "enterprise",
    type: "employment",
    title: "Indigenous Reconciliation Plan 2025–2027: implement Indigenous employment strategy",
    detail: "Implement an Indigenous employment strategy under CN's 2025 to 2027 Indigenous Reconciliation Plan.",
    targetText: "Indigenous employment strategy by 2027",
    targetYear: 2027,
    history: [h("2025", "committed", 20), h("2026", "in_progress", 36)],
    source: SRC.cn,
  }),
  mk({
    id: "cm-cn-proc",
    orgName: "CN (Canadian National Railway)",
    sector: "transport",
    orgSize: "enterprise",
    type: "procurement",
    title: "Embed Indigenous engagement questionnaire into all Canadian RFPs",
    detail: "Embed an Indigenous engagement questionnaire into all Canadian requests for proposals; CN reports this completed.",
    targetText: "questionnaire in all Canadian RFPs",
    targetYear: 2025,
    history: [h("2024", "in_progress", 60), h("2025", "reported", 100)],
    source: SRC.cn,
  }),

  // ── Additional real companies (public reconciliation / ESG disclosures) ──
  mk({
    id: "cm-sunlife-emp", orgName: "Sun Life", sector: "finance", orgSize: "enterprise", type: "employment",
    title: "Reach 1% Indigenous representation across all levels in Canada by 2030", targetYear: 2030,
    history: [h("2024", "committed", 15), h("2025", "in_progress", 25)],
    source: { label: "Sun Life Indigenous Commitments", url: "https://www.sunlife.ca/en/about-us/sustainability/sun-life-indigenous-commitments/" },
    detail: "Sun Life's aspirational goal to grow Indigenous representation across all levels of its Canadian workforce.",
    targetText: "1% Indigenous representation by 2030",
  }),
  mk({
    id: "cm-cibc-gov", orgName: "CIBC", sector: "finance", orgSize: "enterprise", type: "governance",
    title: "Set and report measurable reconciliation KPIs via the Reconciliation Action Committee", targetYear: 2026,
    history: [h("2024", "in_progress", 35), h("2025", "in_progress", 45)],
    source: { label: "CIBC Reconciliation", url: "https://www.cibc.com/en/about-cibc/corporate-profile/reconciliation.html" },
    detail: "CIBC's Reconciliation Action Committee develops measurable commitments and reports progress against KPIs annually.",
    targetText: "annual KPI reporting",
  }),
  mk({
    id: "cm-nationalbank-gov", orgName: "National Bank of Canada", sector: "finance", orgSize: "enterprise", type: "governance",
    title: "Maintain CCIB Partnership Accreditation in Indigenous Relations (PAIR)", targetYear: 2025,
    history: [h("2023", "in_progress", 60), h("2024", "reported", 100)],
    source: { label: "National Bank — Indigenous", url: "https://www.nbc.ca/personal/switch-national-bank/indigenous.html" },
    detail: "National Bank completed its second year of CCIB Partnership Accreditation in Indigenous Relations.",
    targetText: "PAIR maintained",
  }),
  mk({
    id: "cm-atb-proc", orgName: "ATB Financial", sector: "finance", orgSize: "large", type: "procurement",
    title: "Increase Indigenous supplier representation (Accessible Procurement pillar, 2025–2027)", targetYear: 2027,
    history: [h("2025", "committed", 15), h("2026", "in_progress", 30)],
    source: { label: "ATB Truth & Reconciliation Action Plan", url: "https://www.atb.com/company/news/releases/atb-introduces-truth-and-reconciliation-action-plan/" },
    detail: "ATB's Truth and Reconciliation Action Plan (14 commitments) includes an Accessible Procurement pillar to source more from Indigenous businesses.",
    targetText: "more Indigenous suppliers by 2027",
  }),
  mk({
    id: "cm-vancity-gov", orgName: "Vancity", sector: "finance", orgSize: "large", type: "governance",
    title: "Advance reconciliation and pursue CCIB PAIR certification", targetYear: 2025,
    history: [h("2023", "in_progress", 50), h("2024", "in_progress", 65)],
    source: { label: "Vancity — Committed to Reconciliation", url: "https://news.vancity.com/community/reconciliation" },
    detail: "Reconciliation is a core organizational value; Vancity is a founding partner of Reconciliation Canada and pursues PAIR certification.",
    targetText: "PAIR certification",
  }),
  mk({
    id: "cm-nutrien-proc", orgName: "Nutrien", sector: "mining", orgSize: "enterprise", type: "procurement",
    title: "25x25: at least 25% of relevant potash spend with Indigenous suppliers by 2025 (exceeded)", targetYear: 2025,
    history: [h("2022", "in_progress", 70), h("2023", "reported", 90), h("2024", "reported", 100)],
    source: { label: "Nutrien — Indigenous Content Playbook", url: "https://www.nutrien.com/news/stories/a-billion-dollar-playbook" },
    detail: "Nutrien's '25x25' target; exceeded every year, with $567M of $1.1B potash procurement (2020–2024) going to Indigenous-owned suppliers.",
    targetText: "at least 25% of relevant potash spend (exceeded)",
  }),
  mk({
    id: "cm-cameco-proc", orgName: "Cameco", sector: "mining", orgSize: "large", type: "procurement",
    title: "Sustain about 79% northern local procurement in Saskatchewan operations", targetYear: 2025,
    history: [h("2023", "reported", 85), h("2024", "reported", 90)],
    source: { label: "Cameco — Workforce and Communities", url: "https://www.cameco.com/about/sustainability/workforce-and-communities" },
    detail: "Cameco's northern Saskatchewan operations target roughly 79% local procurement, sustaining strong Indigenous and northern supplier participation.",
    targetText: "~79% northern local procurement",
  }),
  mk({
    id: "cm-agnico-emp", orgName: "Agnico Eagle", sector: "mining", orgSize: "enterprise", type: "employment",
    title: "Grow Indigenous employment across Canadian operations (first Canadian-led miner RAP)", targetYear: 2026,
    history: [h("2024", "in_progress", 45), h("2025", "in_progress", 55)],
    source: { label: "Agnico Eagle — Reconciliation", url: "https://www.agnicoeagle.com/English/sustainability/social/reconciliation-with-indigenous-peoples/default.aspx" },
    detail: "First Canadian-based miner to publish a RAP; about 18% of the Detour Lake workforce is First Nations, with an Indigenous Advisory Committee added in 2025.",
    targetText: "higher Indigenous employment",
  }),
  mk({
    id: "cm-enbridge-proc", orgName: "Enbridge", sector: "energy", orgSize: "enterprise", type: "procurement",
    title: "Reach C$3B cumulative Indigenous procurement spend by 2030", targetYear: 2030,
    history: [h("2024", "in_progress", 55), h("2025", "reported", 67)],
    source: { label: "Enbridge · Indigenous procurement", url: "https://www.enbridge.com/stories/2026/june/national-indigenous-peoples-day-enbridge-committed-respectful-engagement-collaboration" },
    detail: "Enbridge set an external procurement target of an additional C$1B, on top of about C$2B already spent, for roughly C$3B cumulative Indigenous spend by 2030.",
    targetText: "C$3B cumulative by 2030",
  }),
  mk({
    id: "cm-bchydro-rel", orgName: "BC Hydro", sector: "energy", orgSize: "enterprise", type: "relationships",
    title: "Offer a minimum 25% equity ownership to affected Indigenous communities on new projects", targetYear: 2026,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 50)],
    source: { label: "BC Hydro Service Plan 2025/26–2027/28", url: "https://www.bcbudget.gov.bc.ca/2025/sp/pdf/agency/bchydro.pdf" },
    detail: "BC Hydro's commitment to offer at least 25% equity ownership to Indigenous communities affected by new generation and transmission projects.",
    targetText: "at least 25% equity on new projects",
  }),
  mk({
    id: "cm-hydroquebec-proc", orgName: "Hydro-Québec", sector: "energy", orgSize: "enterprise", type: "procurement",
    title: "Grow contracts awarded to Indigenous firms", targetYear: 2025,
    history: [h("2023", "in_progress", 65), h("2024", "reported", 80)],
    source: { label: "Hydro-Québec — Indigenous relations", url: "https://www.hydroquebec.com/indigenous-relations/relations.html" },
    detail: "Hydro-Québec awarded about $143M in contracts to Indigenous firms (2020) and runs targeted Indigenous recruitment and mentorship.",
    targetText: "grow Indigenous contracting",
  }),
  mk({
    id: "cm-manitobahydro-rel", orgName: "Manitoba Hydro", sector: "energy", orgSize: "large", type: "relationships",
    title: "Procure up to 600 MW of Indigenous majority-owned wind power", targetYear: 2027,
    history: [h("2025", "committed", 20), h("2026", "in_progress", 40)],
    source: { label: "Manitoba Hydro — Call for Wind Power", url: "https://www.hydro.mb.ca/corporate/call-for-wind-power/" },
    detail: "Under the Manitoba Affordable Energy Plan, Manitoba Hydro is procuring up to 600 MW of Indigenous majority-owned wind generation.",
    targetText: "up to 600 MW Indigenous-owned wind",
  }),
  mk({
    id: "cm-imperial-proc", orgName: "Imperial Oil", sector: "energy", orgSize: "enterprise", type: "procurement",
    title: "Sustain and grow spend with Indigenous businesses (over $7B since 2008)", targetYear: 2025,
    history: [h("2023", "reported", 80), h("2024", "reported", 85)],
    source: { label: "Imperial — Indigenous engagement", url: "https://www.imperialoil.ca/sustainability/indigenous-engagement" },
    detail: "Imperial reports more than $7B invested with Indigenous businesses since 2008, including record annual spend.",
    targetText: "over $7B cumulative since 2008",
  }),
  mk({
    id: "cm-loblaw-proc", orgName: "Loblaw Companies", sector: "retail", orgSize: "enterprise", type: "procurement",
    title: "Grow Indigenous-owned suppliers in the supply chain (CCAB partnership)", targetYear: 2026,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "Loblaw — Commitment to reconciliation", url: "https://www.loblaw.ca/en/our-commitment-to-reconciliation/" },
    detail: "Loblaw's reconciliation action plan partners with CCAB (1,000+ Indigenous businesses) to grow Indigenous-owned suppliers in its supply chain.",
    targetText: "more Indigenous suppliers",
  }),
  mk({
    id: "cm-deloitte-proc", orgName: "Deloitte Canada", sector: "consulting", orgSize: "enterprise", type: "procurement",
    title: "Exceed a 5% Indigenous procurement spend goal (corporate Canada's first RAP)", targetYear: 2025,
    history: [h("2022", "reported", 90), h("2023", "reported", 100)],
    source: { label: "Deloitte Canada — Reconciliation Action Plan", url: "https://www.deloitte.com/ca/en/about/story/purpose-values/reconciliation-action-plan.html" },
    detail: "Deloitte published corporate Canada's first RAP; it exceeds a 5% Indigenous procurement spend goal and earned Gold-level CCIB PAIR.",
    targetText: "over 5% Indigenous procurement (exceeded)",
  }),
  mk({
    id: "cm-cpkc-proc", orgName: "CPKC (Canadian Pacific Kansas City)", sector: "transport", orgSize: "enterprise", type: "procurement",
    title: "Source products and services from Indigenous-owned businesses across the network", targetYear: 2027,
    history: [h("2024", "committed", 20), h("2025", "in_progress", 35)],
    source: { label: "CPKC — CCIB member profile", url: "https://www.ccab.com/main/ccab_member/canadian-pacific-kansas-city/" },
    detail: "CPKC is pursuing new products and services from Indigenous-owned businesses and encourages Indigenous vendors across its network.",
    targetText: "grow Indigenous vendor sourcing",
  }),
  mk({
    id: "cm-canadapost-proc", orgName: "Canada Post", sector: "government", orgSize: "enterprise", type: "procurement",
    title: "Implement an Indigenous procurement policy under the reconciliation strategy", targetYear: 2025,
    history: [h("2023", "in_progress", 40), h("2024", "in_progress", 55)],
    source: { label: "Canada Post — Indigenous reconciliation strategy", url: "https://www.canadapost-postescanada.ca/cpc/en/our-company/indigenous-reconciliation.page" },
    detail: "Canada Post's Indigenous reconciliation strategy redefines relationships with Indigenous-owned companies and introduces an Indigenous procurement policy.",
    targetText: "Indigenous procurement policy",
  }),
  mk({
    id: "cm-ubc-proc", orgName: "University of British Columbia", sector: "education", orgSize: "large", type: "procurement",
    title: "Implement an Indigenous procurement strategy under the Indigenous Strategic Plan", targetYear: 2026,
    history: [h("2024", "in_progress", 40), h("2025", "in_progress", 50)],
    source: { label: "UBC Indigenous Strategic Plan", url: "https://isp.ubc.ca/" },
    detail: "UBC's Indigenous Strategic Plan prioritizes goods and services from Indigenous businesses and strengthens Indigenous recruitment and retention.",
    targetText: "prioritize Indigenous suppliers",
  }),
  mk({
    id: "cm-pwc-gov", orgName: "PwC Canada", sector: "consulting", orgSize: "enterprise", type: "governance",
    title: "Commit to the CCIB Progressive Aboriginal Relations (PAR) program", targetYear: 2026,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "PwC Canada · Truth and Reconciliation", url: "https://www.pwc.com/ca/en/about-us/diversity-inclusion/truth-reconciliation.html" },
    detail: "PwC Canada committed to the CCIB Progressive Aboriginal Relations (PAR) program as part of its reconciliation journey.",
    targetText: "PAR commitment",
  }),
  mk({
    id: "cm-kpmg-gov", orgName: "KPMG Canada", sector: "consulting", orgSize: "enterprise", type: "governance",
    title: "Advance the Truth & Reconciliation Action Plan (PAR-committed with CCAB)", targetYear: 2026,
    history: [h("2023", "committed", 30), h("2024", "in_progress", 50)],
    source: { label: "KPMG Canada · Truth & Reconciliation Action Plan", url: "https://kpmg.com/ca/en/home/about/inclusion-diversity-equity/kpmg-truth-reconciliation-action-plan.html" },
    detail: "KPMG became PAR-committed with CCAB within the first year of implementing its Truth and Reconciliation Action Plan.",
    targetText: "PAR-committed",
  }),
  mk({
    id: "cm-westjet-rel", orgName: "WestJet", sector: "transport", orgSize: "large", type: "relationships",
    title: "Sponsor the Indigenous Tourism Association of Canada (ITAC)", targetYear: 2025,
    history: [h("2024", "committed", 40), h("2025", "reported", 100)],
    source: { label: "WestJet · Indigenous tourism partnership", url: "https://www.travelpulse.ca/news/airlines-airports/westjet-and-canadian-tire-join-forces" },
    detail: "WestJet committed $100,000 to sponsor the Indigenous Tourism Association of Canada (ITAC).",
    targetText: "$100K ITAC sponsorship",
  }),

  // ── Batch 2: more sectors (telecom, forestry, construction, health, education) ──
  mk({
    id: "cm-rogers-emp", orgName: "Rogers Communications", sector: "telecom", orgSize: "enterprise", type: "employment",
    title: "Double Indigenous team member representation by 2025", targetYear: 2025,
    history: [h("2023", "in_progress", 60), h("2024", "in_progress", 80)],
    source: { label: "Rogers · Truth & Reconciliation", url: "https://about.rogers.com/stories/rogers-truth-and-reconciliation-commitment-statement/" },
    detail: "Rogers aims to double Indigenous representation among its team members and pursues podium PAR status with CCAB.",
    targetText: "double Indigenous representation by 2025",
  }),
  mk({
    id: "cm-bell-rel", orgName: "Bell Canada", sector: "telecom", orgSize: "enterprise", type: "relationships",
    title: "Advance broadband & wireless access to rural and remote First Nations by 2030", targetYear: 2030,
    history: [h("2024", "committed", 25), h("2025", "in_progress", 40)],
    source: { label: "Bell · Indigenous connectivity", url: "https://www.bce.ca/news-and-media/releases/show/bell-canada-and-national-indigenous-connectivity-inc-to-advance-broadband-and-wireless-access-for-rural-and-remote-first-nations-communities" },
    detail: "Bell's reconciliation agreement with National Indigenous Connectivity Inc. to expand connectivity in rural and remote First Nations communities by 2030.",
    targetText: "connectivity for First Nations by 2030",
  }),
  mk({
    id: "cm-westfraser-emp", orgName: "West Fraser", sector: "forestry", orgSize: "enterprise", type: "employment",
    title: "Achieve equitable Indigenous representation in the workforce", targetYear: 2026,
    history: [h("2024", "in_progress", 40), h("2025", "in_progress", 50)],
    source: { label: "West Fraser · Indigenous Relations", url: "https://www.westfraser.com/sustainability/social/indigenous-relations" },
    detail: "West Fraser engages 100+ Indigenous governments and communities and targets equitable Indigenous representation via recruitment, retention, scholarships and procurement.",
    targetText: "equitable Indigenous representation",
  }),
  mk({
    id: "cm-canfor-proc", orgName: "Canfor", sector: "forestry", orgSize: "enterprise", type: "procurement",
    title: "Grow Indigenous vendor spend (6.1% of Canadian operations spend in 2024)", targetYear: 2026,
    history: [h("2023", "in_progress", 55), h("2024", "reported", 70)],
    source: { label: "Canfor · Indigenous Relations", url: "https://www.canfor.com/stewardship/sustainability/indigenous-relations" },
    detail: "In 2024, 6.13% of Canfor's Canadian operations spend was with Indigenous vendors, guided by its Indigenous Engagement Strategy.",
    targetText: "grow Indigenous vendor spend (6.1% in 2024)",
  }),
  mk({
    id: "cm-ahs-emp", orgName: "Alberta Health Services", sector: "health", orgSize: "enterprise", type: "employment",
    title: "Build an Indigenous workforce under the Indigenous Health Commitments (Roadmap to Wellness)", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "AHS · Indigenous Health", url: "https://www.albertahealthservices.ca/info/Page11949.aspx" },
    detail: "AHS's Indigenous Health Commitments: Roadmap to Wellness guides building an Indigenous workforce and achieving health equity with Indigenous peoples.",
    targetText: "grow Indigenous workforce",
  }),
  mk({
    id: "cm-vch-cul", orgName: "Vancouver Coastal Health", sector: "health", orgSize: "large", type: "cultural_learning",
    title: "Embed Indigenous cultural safety across care (In Plain Sight Rec. 10)", targetYear: 2026,
    history: [h("2024", "in_progress", 45), h("2025", "in_progress", 60)],
    source: { label: "Vancouver Coastal Health · Indigenous Health", url: "https://www.vch.ca/en/about-us/indigenous-health" },
    detail: "VCH is creating culturally safer spaces and care aligned with the In Plain Sight report's Recommendation 10.",
    targetText: "cultural safety across care",
  }),
  mk({
    id: "cm-ualberta-rel", orgName: "University of Alberta", sector: "education", orgSize: "large", type: "relationships",
    title: "Deliver the Braiding Past, Present and Future Indigenous Strategic Plan", targetYear: 2026,
    history: [h("2024", "in_progress", 40), h("2025", "in_progress", 55)],
    source: { label: "U of Alberta · Indigenous Strategic Plan", url: "https://www.ualberta.ca/en/indigenous/strategic-plan/index.html" },
    detail: "The University of Alberta's Indigenous Strategic Plan drives Indigenous recruitment, partnership and institutional change.",
    targetText: "Indigenous Strategic Plan",
  }),
  mk({
    id: "cm-uoft-gov", orgName: "University of Toronto", sector: "education", orgSize: "large", type: "governance",
    title: "Advance the TRC response (Answering the Call) and Indigenous Substantiation", targetYear: 2026,
    history: [h("2024", "in_progress", 45), h("2025", "in_progress", 60)],
    source: { label: "U of T · Institutional Equity Commitments", url: "https://commitments.utoronto.ca/" },
    detail: "U of T's Office of Indigenous Initiatives implements its TRC response and a new Indigenous Substantiation framework to protect Indigenous-designated opportunities.",
    targetText: "TRC calls + substantiation",
  }),
  mk({
    id: "cm-aecon-proc", orgName: "Aecon", sector: "construction", orgSize: "enterprise", type: "procurement",
    title: "Enhance Indigenous procurement as a CCIB Supply Change Champion", targetYear: 2026,
    history: [h("2023", "in_progress", 50), h("2024", "in_progress", 62)],
    source: { label: "Aecon · Indigenous Relations", url: "https://www.aecon.com/indigenous-relations" },
    detail: "Aecon adopted a Reconciliation Action Plan (2022, per TRC Call to Action #92) and is a CCIB Supply Change Indigenous Procurement Champion.",
    targetText: "grow Indigenous procurement",
  }),
  mk({
    id: "cm-ikea-cul", orgName: "IKEA Canada", sector: "retail", orgSize: "enterprise", type: "cultural_learning",
    title: "Advance the Indigenous Reconciliation Strategy across stores", targetYear: 2026,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "IKEA Canada · Reconciliation", url: "https://www.newswire.ca/news-releases/ikea-canada-marks-ongoing-indigenous-reconciliation-journey-with-indigenous-inspired-spaces-at-ikea-winnipeg-896758023.html" },
    detail: "IKEA Canada's Indigenous Reconciliation Strategy builds respectful relationships, including Indigenous-influenced spaces in stores.",
    targetText: "reconciliation strategy across stores",
  }),
  mk({
    id: "cm-newmont-proc", orgName: "Newmont", sector: "mining", orgSize: "enterprise", type: "procurement",
    title: "Increase supplier diversity with Indigenous businesses", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "Newmont · Local Procurement", url: "https://operations.newmont.com/local-procurement" },
    detail: "Newmont engages local and Indigenous businesses and is increasing Indigenous supplier diversity across its operations.",
    targetText: "grow Indigenous supplier diversity",
  }),

  // ── Batch 3: insurance, aviation/rail, utilities, mining, construction ──
  mk({
    id: "cm-cooperators-emp", orgName: "Co-operators", sector: "finance", orgSize: "large", type: "employment",
    title: "Invest $1M in an Indigenous Youth Employability Initiative and grow Indigenous careers", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "Co-operators · Truth and Reconciliation", url: "https://www.cooperators.ca/en/about-us/reconciliation" },
    detail: "Co-operators launched a $1M Indigenous Youth Employability Initiative and an Indigenous Advisory Council, and is expanding Indigenous career opportunities over three years.",
    targetText: "$1M youth employability + hiring",
  }),
  mk({
    id: "cm-canadalife-gov", orgName: "Canada Life", sector: "finance", orgSize: "enterprise", type: "governance",
    title: "Act on a TRC Call to Action each year (Winnipeg's Indigenous Accord)", targetYear: 2026,
    history: [h("2024", "in_progress", 40), h("2025", "in_progress", 55)],
    source: { label: "Canada Life · Who we are", url: "https://www.canadalife.com/about-us/who-we-are.html" },
    detail: "Canada Life and IG Wealth Management are signatories of Winnipeg's Indigenous Accord, committing to advance a TRC Call to Action each year.",
    targetText: "one TRC action per year",
  }),
  mk({
    id: "cm-manulife-cul", orgName: "Manulife", sector: "finance", orgSize: "enterprise", type: "cultural_learning",
    title: "Advance reconciliation via Indigenous Legacy Spaces and education", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "Manulife · Our impact", url: "https://www.manulife.ca/about-us/our-impact.html" },
    detail: "Manulife opened Indigenous Legacy Spaces at its Toronto and Waterloo offices to advance Indigenous education and awareness, supported by its IPTA employee group.",
    targetText: "Legacy Spaces + education",
  }),
  mk({
    id: "cm-viarail-proc", orgName: "VIA Rail", sector: "transport", orgSize: "large", type: "procurement",
    title: "Grow Indigenous recruitment and procurement (pursuing CCAB PAR)", targetYear: 2026,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "VIA Rail · Indigenous communities", url: "https://www.viarail.ca/en/offers/indigenous-communities" },
    detail: "VIA Rail is building lasting economic partnerships through targeted recruitment and procurement and is pursuing CCAB PAR certification.",
    targetText: "recruitment + procurement (PAR)",
  }),
  mk({
    id: "cm-pearson-rel", orgName: "Toronto Pearson (GTAA)", sector: "transport", orgSize: "enterprise", type: "relationships",
    title: "Invest $780K to strengthen Indigenous-led organizations", targetYear: 2025,
    history: [h("2024", "in_progress", 60), h("2025", "reported", 100)],
    source: { label: "Toronto Pearson · Indigenous investment", url: "https://www.internationalairportreview.com/toronto-pearson-invests-780000-to-strengthen-indigenous-led-organisations-and-advance-reconciliation-across-canada/539389.article" },
    detail: "Toronto Pearson (Greater Toronto Airports Authority) invested $780,000 to strengthen Indigenous-led organizations and advance reconciliation.",
    targetText: "$780K to Indigenous organizations",
  }),
  mk({
    id: "cm-saskpower-proc", orgName: "SaskPower", sector: "energy", orgSize: "enterprise", type: "procurement",
    title: "Exceed the Indigenous procurement target (15.1% of Sask supplier POs, $118M in 2024-25)", targetYear: 2025,
    history: [h("2023", "reported", 90), h("2024", "reported", 100)],
    source: { label: "SaskPower · Diversity and Inclusion", url: "https://www.saskpower.com/about-us/Our-Company/Commitment-to-Diversity-and-Inclusion" },
    detail: "SaskPower's Indigenous procurement reached 15.1% of purchase orders to Saskatchewan suppliers ($118M in 2024-25), exceeding its 11% target.",
    targetText: "15.1% of Sask supplier POs (target 11%)",
  }),
  mk({
    id: "cm-ioc-proc", orgName: "Iron Ore Company of Canada", sector: "mining", orgSize: "enterprise", type: "procurement",
    title: "Deliver employment & procurement benefits under the Innu reconciliation agreement", targetYear: 2026,
    history: [h("2024", "in_progress", 50), h("2025", "in_progress", 62)],
    source: { label: "Iron Ore Company of Canada · Indigenous participation", url: "https://www.ironore.ca/en/sustainability/indigenous-participation" },
    detail: "IOC's 2020 reconciliation and collaboration agreement with Innu communities gives first consideration for employment and procurement opportunities.",
    targetText: "employment & procurement benefits",
  }),
  mk({
    id: "cm-glencore-emp", orgName: "Glencore Canada", sector: "mining", orgSize: "enterprise", type: "employment",
    title: "Attract and retain Inuit employees via the Tamatumani program", targetYear: 2026,
    history: [h("2024", "in_progress", 45), h("2025", "in_progress", 55)],
    source: { label: "Glencore Canada · Community", url: "https://www.glencore.ca/en/sustainability/community" },
    detail: "Glencore's Raglan Mine Tamatumani program aims to attract and retain the largest possible number of Inuit employees and contractors.",
    targetText: "grow Inuit employment",
  }),
  mk({
    id: "cm-ellisdon-gov", orgName: "EllisDon", sector: "construction", orgSize: "enterprise", type: "governance",
    title: "Maintain CCIB PAIR (Bronze) and grow Indigenous partnerships", targetYear: 2026,
    history: [h("2024", "in_progress", 55), h("2025", "in_progress", 65)],
    source: { label: "EllisDon · Indigenous Relations", url: "https://www.ellisdon.com/indigenous-relations" },
    detail: "EllisDon holds CCIB PAIR Bronze certification and maintains a database of Indigenous partners to engage across projects.",
    targetText: "PAIR Bronze + partnerships",
  }),
  mk({
    id: "cm-graham-emp", orgName: "Graham Construction", sector: "construction", orgSize: "large", type: "employment",
    title: "Maximize Indigenous workforce and vendors via the G3N (Three Nations) brand", targetYear: 2026,
    history: [h("2024", "in_progress", 60), h("2025", "reported", 75)],
    source: { label: "Graham · Indigenous Engagement", url: "https://www.grahambuilds.com/about-graham/indigenous-engagement/" },
    detail: "Graham's G3N (Three Nations) brand maximizes local Indigenous trade contractors, suppliers and workers, reaching 80%+ local workforce content on some projects.",
    targetText: "80%+ local workforce content",
  }),
  mk({
    id: "cm-pcl-rel", orgName: "PCL Construction", sector: "construction", orgSize: "enterprise", type: "relationships",
    title: "Ensure full and fair Indigenous participation in projects", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "PCL · CCIB member", url: "https://www.ccib.ca/main/member/pcl-construction/" },
    detail: "PCL commits to full and fair Indigenous participation in the projects it constructs, building long-term community relationships.",
    targetText: "full & fair participation",
  }),

  // ── Batch 4: telecom, crown financial agencies, utilities ──
  mk({
    id: "cm-telus-proc", orgName: "TELUS", sector: "telecom", orgSize: "enterprise", type: "procurement",
    title: "Invest 7.5% via the Pollinator Fund in Indigenous-owned companies by 2026", targetYear: 2026,
    history: [h("2023", "in_progress", 60), h("2024", "reported", 80)],
    source: { label: "TELUS · Indigenous Reconciliation", url: "https://www.telus.com/en/social-impact/connecting-canada/indigenous-reconciliation" },
    detail: "First Canadian tech company to publish a reconciliation action plan (2021); Silver CCIB PAIR; 20,000+ team members completed Indigenous cultural-awareness training; targeting 7.5% of Pollinator Fund invested in Indigenous-owned companies by 2026.",
    targetText: "7.5% of Pollinator Fund by 2026",
  }),
  mk({
    id: "cm-bdc-rel", orgName: "Business Development Bank of Canada", sector: "government", orgSize: "enterprise", type: "relationships",
    title: "Grow Indigenous entrepreneur financing (Indigenous Growth Fund with NACCA)", targetYear: 2026,
    history: [h("2024", "in_progress", 55), h("2025", "in_progress", 65)],
    source: { label: "BDC · CCAB member", url: "https://www.ccab.com/main/ccab_member/business-development-bank-of-canada/" },
    detail: "BDC co-created the $150M Indigenous Growth Fund with NACCA and offers Indigenous Entrepreneur Loans to expand capital for Indigenous business owners.",
    targetText: "$150M Indigenous Growth Fund",
  }),
  mk({
    id: "cm-edc-rel", orgName: "Export Development Canada", sector: "government", orgSize: "enterprise", type: "relationships",
    title: "Support Indigenous-owned businesses to grow and export internationally", targetYear: 2026,
    history: [h("2024", "committed", 40), h("2025", "in_progress", 50)],
    source: { label: "EDC · Indigenous business", url: "https://www.edc.ca/en/campaign/indigenous-business.html" },
    detail: "EDC supports Indigenous-owned and -led businesses to grow and succeed in international trade.",
    targetText: "support Indigenous exporters",
  }),
  mk({
    id: "cm-cib-rel", orgName: "Canada Infrastructure Bank", sector: "government", orgSize: "enterprise", type: "relationships",
    title: "Invest at least $3B benefiting Indigenous communities (surpassed $1B in Indigenous equity)", targetYear: 2027,
    history: [h("2024", "in_progress", 55), h("2025", "reported", 70)],
    source: { label: "Canada Infrastructure Bank · Indigenous", url: "https://cib-bic.ca/en/indigenous-infra/" },
    detail: "The CIB targets at least $3B in projects benefiting Indigenous communities and has surpassed $1B in funding for Indigenous projects, including a $1B Indigenous equity loan program.",
    targetText: "at least $3B benefiting Indigenous communities",
  }),
  mk({
    id: "cm-opg-rel", orgName: "Ontario Power Generation", sector: "energy", orgSize: "enterprise", type: "relationships",
    title: "Create $1B of economic impact for Indigenous communities over 10 years", targetYear: 2030,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "Ontario Power Generation · Indigenous economic inclusion", url: "https://www.niedb-cndea.ca/success-stories/ontario-power-generation-powering-the-way-for-indigenous-economic-inclusion/" },
    detail: "OPG committed to creating $1B of economic impact for Indigenous communities and businesses over 10 years through operations, projects and initiatives.",
    targetText: "$1B economic impact over 10 years",
  }),

  // ── Batch 5: aerospace, food/agriculture, media, ports, more crown ──
  mk({
    id: "cm-cae-proc", orgName: "CAE", sector: "aerospace", orgSize: "enterprise", type: "procurement",
    title: "Build an Indigenous supplier network (3,000+ businesses) and Indigenous awareness training", targetYear: 2026,
    history: [h("2023", "in_progress", 50), h("2024", "in_progress", 62)],
    source: { label: "CAE · Indigenous relations", url: "https://www.cae.com" },
    detail: "CAE created an Indigenous Supplier Network procurement database of 3,000+ Indigenous businesses, launched mandatory Indigenous Awareness training (2022), and formed an Indigenous Advisory Board.",
    targetText: "3,000+ supplier network + training",
  }),
  mk({
    id: "cm-mapleleaf-emp", orgName: "Maple Leaf Foods", sector: "agriculture", orgSize: "enterprise", type: "employment",
    title: "Increase BIPOC (incl. Indigenous) representation in management to 25% by 2030", targetYear: 2030,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "Maple Leaf Foods · Diversity, equity & inclusion", url: "https://www.mapleleaffoods.com/our-commitments/people/diversity-equity-and-inclusion/" },
    detail: "Maple Leaf Foods targets 25% BIPOC (including Indigenous) representation in management by 2030 and runs an Indigenous Friends Circle.",
    targetText: "25% BIPOC management by 2030",
  }),
  mk({
    id: "cm-sobeys-gov", orgName: "Sobeys", sector: "retail", orgSize: "enterprise", type: "governance",
    title: "Pursue CCAB Progressive Aboriginal Relations (PAR) accreditation", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "Sobeys · Diversity, equity & inclusion", url: "https://dei.sobeys.com/en/" },
    detail: "Sobeys follows the CCAB Truth & Reconciliation framework and is pursuing PAR accreditation, unique among Canadian grocers.",
    targetText: "pursue PAR accreditation",
  }),
  mk({
    id: "cm-fcl-proc", orgName: "Federated Co-operatives", sector: "retail", orgSize: "enterprise", type: "procurement",
    title: "Advance supply-chain diversity under the Indigenous strategy", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "Federated Co-operatives · Suppliers", url: "https://www.fcl.crs/our-business/suppliers" },
    detail: "FCL's Indigenous strategy is a roadmap for economic reconciliation, embedding Indigenous engagement and supply-chain diversity across the Co-operative Retailing System.",
    targetText: "Indigenous supply-chain diversity",
  }),
  mk({
    id: "cm-portvan-rel", orgName: "Port of Vancouver (Vancouver Fraser Port Authority)", sector: "transport", orgSize: "enterprise", type: "relationships",
    title: "Establish a $5.5M Indigenous Legacy Benefit Fund + employment/procurement collaboration", targetYear: 2026,
    history: [h("2024", "committed", 40), h("2025", "in_progress", 55)],
    source: { label: "Vancouver Fraser Port Authority · Indigenous relations", url: "https://www.portvancouver.com/community/indigenous-relations" },
    detail: "The Vancouver Fraser Port Authority is establishing a $5.5M Indigenous Legacy Benefit Fund and collaborating on employment, procurement, training and skills development.",
    targetText: "$5.5M Indigenous legacy fund",
  }),
  mk({
    id: "cm-cbc-proc", orgName: "CBC/Radio-Canada", sector: "media", orgSize: "enterprise", type: "procurement",
    title: "Include more Indigenous-owned vendors under the National Indigenous Strategy", targetYear: 2026,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "CBC/Radio-Canada · National Indigenous Strategy", url: "https://cbc.radio-canada.ca/en/your-public-broadcaster/blog/oped-road-to-reconcilliation" },
    detail: "CBC/Radio-Canada's National Indigenous Strategy ('Strengthening Relations, Walking Together') commits to including more Indigenous-owned vendors in procurement.",
    targetText: "more Indigenous vendors",
  }),
  mk({
    id: "cm-bclc-proc", orgName: "BCLC", sector: "government", orgSize: "enterprise", type: "procurement",
    title: "Implement a new Indigenous Procurement Policy", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "BCLC · Indigenous Procurement Policy", url: "https://corporate.bclc.com/articles/our-business/2025/driving-economic-reconciliation--bclc-s-new-indigenous-procureme.html" },
    detail: "BCLC (BC Lottery Corporation) introduced a new Indigenous Procurement Policy to drive economic reconciliation.",
    targetText: "new Indigenous procurement policy",
  }),

  // ── Batch 6: transit authorities, more universities, transmission, engineering ──
  mk({
    id: "cm-translink-proc", orgName: "TransLink", sector: "transport", orgSize: "enterprise", type: "procurement",
    title: "Award at least 5% of active contracts to Indigenous-owned suppliers by 2030", targetYear: 2030,
    history: [h("2024", "committed", 25), h("2025", "in_progress", 40)],
    source: { label: "TransLink · Indigenous Relations", url: "https://www.translink.ca/about-us/about-translink/indigenous-relations" },
    detail: "TransLink's Reconciliation Report commits to a minimum 5% of active contracts with Indigenous-owned and operated suppliers (direct or sub-contractor) by 2030.",
    targetText: "at least 5% of contracts by 2030",
  }),
  mk({
    id: "cm-metrolinx-rel", orgName: "Metrolinx", sector: "transport", orgSize: "enterprise", type: "relationships",
    title: "Advance reconciliation through Indigenous partnerships and Community Benefits", targetYear: 2026,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "Metrolinx · Equity, Diversity and Inclusion", url: "https://www.metrolinx.com/en/about-us/edi" },
    detail: "Metrolinx commits to doing business on a foundation of trust and collaboration with Indigenous partners and connects communities to jobs through its Community Benefits and Supports Program.",
    targetText: "Indigenous partnerships + community benefits",
  }),
  mk({
    id: "cm-mcgill-rel", orgName: "McGill University", sector: "education", orgSize: "large", type: "relationships",
    title: "Implement the 52 Calls to Action on Indigenous studies and education", targetYear: 2026,
    history: [h("2024", "in_progress", 45), h("2025", "in_progress", 55)],
    source: { label: "McGill · Office of Indigenous Initiatives", url: "https://www.mcgill.ca/indigenous/" },
    detail: "McGill's Office of Indigenous Initiatives is implementing the 52 Calls to Action from the Provost's Task Force on Indigenous Studies and Indigenous Education, embedding Indigeneity across the university.",
    targetText: "52 Calls to Action",
  }),
  mk({
    id: "cm-western-rel", orgName: "Western University", sector: "education", orgSize: "large", type: "relationships",
    title: "Deliver Western's first Indigenous Strategic Plan", targetYear: 2026,
    history: [h("2024", "committed", 40), h("2025", "in_progress", 50)],
    source: { label: "Western · Indigenous Initiatives", url: "https://indigenous.uwo.ca/" },
    detail: "Western's Office of Indigenous Initiatives champions the university's first Indigenous Strategic Plan through community-engaged partnerships and campus-wide implementation.",
    targetText: "Indigenous Strategic Plan",
  }),
  mk({
    id: "cm-mcmaster-gov", orgName: "McMaster University", sector: "education", orgSize: "large", type: "governance",
    title: "Implement Indigenous Strategic Directions incl. the leadership & governance goal", targetYear: 2026,
    history: [h("2024", "in_progress", 40), h("2025", "in_progress", 55)],
    source: { label: "McMaster · Indigenous Studies", url: "https://indigenous.mcmaster.ca/" },
    detail: "McMaster's Indigenous Strategic Directions, led by the Indigenous Education Council, sets four goals (research, education, student experience, leadership & governance) and ensures Indigenous participation in decision-making.",
    targetText: "Indigenous Strategic Directions",
  }),
  mk({
    id: "cm-altalink-rel", orgName: "AltaLink", sector: "energy", orgSize: "large", type: "relationships",
    title: "Provide 51% Indigenous equity ownership on transmission lines across their lands", targetYear: 2025,
    history: [h("2023", "in_progress", 70), h("2024", "reported", 85)],
    source: { label: "AltaLink · Indigenous Relations", url: "https://www.altalink.ca/our-commitment/indigenous-relations/" },
    detail: "AltaLink formed partnerships giving the Piikani Nation and Kainai (Blood) Tribe 51% of the equity in the portions of its Southwest 240 kV transmission line on their lands, and targets Indigenous participation proportionate to Alberta's population.",
    targetText: "51% Indigenous equity on transmission",
  }),
  mk({
    id: "cm-atkinsrealis-proc", orgName: "AtkinsRéalis", sector: "consulting", orgSize: "enterprise", type: "procurement",
    title: "Deliver the ReconciliACTION Plan across procurement and recruitment by 2030", targetYear: 2030,
    history: [h("2023", "committed", 30), h("2024", "in_progress", 50), h("2025", "in_progress", 60)],
    source: { label: "AtkinsRéalis · Indigenous relations", url: "https://www.atkinsrealis.com/en/about/indigenous-relations" },
    detail: "AtkinsRéalis launched its ReconciliACTION Plan (2023) with actions to 2030 across procurement, recruitment and project delivery; earned Bronze CCIB PAIR (2024) and became an Indigenous Procurement Champion (2021).",
    targetText: "ReconciliACTION Plan by 2030",
  }),

  // ── Batch 7: airports, airline, utility, health authorities, insurance ──
  mk({
    id: "cm-yyc-rel", orgName: "Calgary Airport Authority", sector: "transport", orgSize: "large", type: "relationships",
    title: "Deliver the Indigenous Reconciliation Strategy (2025) via an Indigenous Advisory Committee", targetYear: 2026,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "Calgary Airport Authority · Indigenous Reconciliation Strategy", url: "https://www.yyc.com/Portals/0/Calgary%20Airport%20Authority%20Indigenous%20Reconciliation%20Strategy_May%202025.pdf" },
    detail: "The Calgary Airport Authority's Indigenous Reconciliation Strategy (May 2025), guided by the TRC Calls to Action and UNDRIP, is delivered through an Action Plan starting in 2025 and an Indigenous Advisory Committee.",
    targetText: "Reconciliation Strategy + Advisory Committee",
  }),
  mk({
    id: "cm-aircanada-emp", orgName: "Air Canada", sector: "transport", orgSize: "enterprise", type: "employment",
    title: "Advance Indigenous careers through the Indigenous ERG, Indspire and a pilot pathway", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "Air Canada · Diversity, Equity and Inclusion", url: "https://www.aircanada.com/ca/en/aco/home/about/diversity-equity-inclusion.html" },
    detail: "Air Canada runs an Indigenous Employee Resource Group led by a Manager of Indigenous Relations & Reconciliation, partners with Indspire on scholarships, and works with the First Nations Technical Institute to help Indigenous students become pilots.",
    targetText: "Indigenous careers + pilot pathway",
  }),
  mk({
    id: "cm-fortisbc-rel", orgName: "FortisBC", sector: "energy", orgSize: "large", type: "relationships",
    title: "Grow Indigenous partnerships as a CCIB PAIR Silver member (58 First Nations served)", targetYear: 2026,
    history: [h("2024", "in_progress", 55), h("2025", "in_progress", 65)],
    source: { label: "FortisBC · Our commitment to Reconciliation", url: "https://www.fortisbc.com/in-your-community/indigenous-relationships-and-reconciliation/our-commitment-to-reconciliation" },
    detail: "FortisBC, a CCIB PAIR Silver member serving 58 First Nations communities, is developing Indigenous business, employment and community partnerships, including a 15 MW solar project with the Upper Nicola Band and Okanagan Nation Alliance.",
    targetText: "PAIR Silver + partnerships",
  }),
  mk({
    id: "cm-sha-emp", orgName: "Saskatchewan Health Authority", sector: "health", orgSize: "enterprise", type: "employment",
    title: "Build a health workforce representative of Indigenous communities (TRC commitment)", targetYear: 2026,
    history: [h("2024", "committed", 35), h("2025", "in_progress", 50)],
    source: { label: "Saskatchewan Health Authority · Truth & Reconciliation", url: "https://www.saskhealthauthority.ca/trc" },
    detail: "SHA's Truth and Reconciliation commitment focuses on closing Indigenous health-outcome gaps, building a more representative workforce, and partnering with the Federation of Sovereign Indigenous Nations and Métis Nation–Saskatchewan.",
    targetText: "representative workforce + partnerships",
  }),
  mk({
    id: "cm-interiorhealth-cul", orgName: "Interior Health", sector: "health", orgSize: "enterprise", type: "cultural_learning",
    title: "Deliver the Indigenous Health & Wellness Strategy 2022–2026", targetYear: 2026,
    history: [h("2024", "in_progress", 45), h("2025", "in_progress", 60)],
    source: { label: "Interior Health · Indigenous Health & Wellness Strategy 2022–2026", url: "https://www.interiorhealth.ca/sites/default/files/PDFS/indigenous-health-wellness-strategy-2022-2026-revised.pdf" },
    detail: "Interior Health's Indigenous Health & Wellness Strategy 2022 to 2026 advances cultural safety, anti-racism and transformative change across its services in British Columbia's interior.",
    targetText: "Indigenous Health & Wellness Strategy",
  }),
  mk({
    id: "cm-intact-gov", orgName: "Intact Financial", sector: "finance", orgSize: "enterprise", type: "governance",
    title: "Advance Truth & Reconciliation actions guided by the Indigenous employee network", targetYear: 2026,
    history: [h("2024", "committed", 30), h("2025", "in_progress", 45)],
    source: { label: "Intact Financial · Diversity, Equity and Inclusion", url: "https://www.intactfc.com/careers/diversity-equity-and-inclusion" },
    detail: "Intact Financial's Indigenous employee network helps shape the company's Truth and Reconciliation actions as part of its diversity, equity and inclusion commitments.",
    targetText: "Truth & Reconciliation actions",
  }),
];
