// Synthetic RAP commitments for the dashboard demo. Spread across sectors,
// org sizes, types, and target years, each with a 2–3 point `history` so the
// "progress over time" view shows real movement. Two are tied to existing
// survey orgs (org-mckinsey, org-cedartrust).
import type {
  Commitment,
  CommitmentType,
  OrgSize,
  ProgressPoint,
  RapType,
  Sector,
} from "./types";

const T = "2025-01-15T00:00:00.000Z";

// Build a Commitment with an explicit, fixed field order. The DynamoDB
// round-trip (itemToCommitment) reconstructs in this SAME order, so the
// dynamo ≡ mock JSON equality in verify.ts holds. current status/% = last point.
function mk(p: {
  id: string;
  orgName: string;
  orgId?: string;
  sector: Sector;
  orgSize: OrgSize;
  type: CommitmentType;
  title: string;
  targetYear: number;
  rapType?: RapType;
  history: ProgressPoint[];
}): Commitment {
  const last = p.history[p.history.length - 1];
  return {
    id: p.id,
    orgName: p.orgName,
    ...(p.orgId !== undefined ? { orgId: p.orgId } : {}),
    sector: p.sector,
    orgSize: p.orgSize,
    type: p.type,
    title: p.title,
    targetYear: p.targetYear,
    ...(p.rapType !== undefined ? { rapType: p.rapType } : {}),
    status: last.status,
    progressPct: last.progressPct,
    history: p.history,
    createdAt: T,
  };
}

const h = (period: string, status: ProgressPoint["status"], progressPct: number): ProgressPoint => ({
  period,
  status,
  progressPct,
});

export const commitmentFixtures: Commitment[] = [
  mk({
    id: "cm-mckinsey-proc",
    orgName: "McKinsey & Company",
    orgId: "org-mckinsey",
    sector: "consulting",
    orgSize: "large",
    type: "procurement",
    title: "Spend 3% of addressable procurement with Indigenous suppliers",
    targetYear: 2025,
    rapType: "innovate",
    history: [h("2023", "committed", 10), h("2024", "in_progress", 45), h("2025", "reported", 70)],
  }),
  mk({
    id: "cm-mckinsey-emp",
    orgName: "McKinsey & Company",
    orgId: "org-mckinsey",
    sector: "consulting",
    orgSize: "large",
    type: "employment",
    title: "Grow Indigenous workforce to 3% via internships + retention",
    targetYear: 2026,
    rapType: "innovate",
    history: [h("2024", "committed", 15), h("2025", "in_progress", 40)],
  }),
  mk({
    id: "cm-cedartrust-proc",
    orgName: "Cedar Trust Bank",
    orgId: "org-cedartrust",
    sector: "finance",
    orgSize: "enterprise",
    type: "procurement",
    title: "Reach $10M annual procurement from Indigenous businesses",
    targetYear: 2025,
    rapType: "stretch",
    history: [h("2023", "in_progress", 40), h("2024", "reported", 74), h("2025", "confirmed", 100)],
  }),
  mk({
    id: "cm-cedartrust-gov",
    orgName: "Cedar Trust Bank",
    orgId: "org-cedartrust",
    sector: "finance",
    orgSize: "enterprise",
    type: "governance",
    title: "Seat 2 First Nations advisors on the RAP steering committee",
    targetYear: 2024,
    rapType: "stretch",
    history: [h("2023", "in_progress", 50), h("2024", "confirmed", 100)],
  }),
  mk({
    id: "cm-northgold-proc",
    orgName: "Northgold Resources",
    sector: "mining",
    orgSize: "enterprise",
    type: "procurement",
    title: "Award 15% of site services to Indigenous-owned contractors",
    targetYear: 2026,
    rapType: "elevate",
    history: [h("2023", "committed", 20), h("2024", "in_progress", 55), h("2025", "reported", 80)],
  }),
  mk({
    id: "cm-northgold-rel",
    orgName: "Northgold Resources",
    sector: "mining",
    orgSize: "enterprise",
    type: "relationships",
    title: "Sign impact-benefit agreements with 3 host nations",
    targetYear: 2025,
    rapType: "elevate",
    history: [h("2023", "in_progress", 35), h("2024", "reported", 66), h("2025", "confirmed", 100)],
  }),
  mk({
    id: "cm-prairiepower-emp",
    orgName: "Prairie Power",
    sector: "energy",
    orgSize: "large",
    type: "employment",
    title: "Apprenticeship pipeline: 50 Indigenous trades roles",
    targetYear: 2026,
    rapType: "stretch",
    history: [h("2024", "committed", 12), h("2025", "in_progress", 38)],
  }),
  mk({
    id: "cm-prairiepower-cul",
    orgName: "Prairie Power",
    sector: "energy",
    orgSize: "large",
    type: "cultural_learning",
    title: "Cultural competency training for all field staff",
    targetYear: 2024,
    rapType: "innovate",
    history: [h("2023", "in_progress", 60), h("2024", "reported", 85)],
  }),
  mk({
    id: "cm-mapleretail-proc",
    orgName: "Maple Retail Co-op",
    sector: "retail",
    orgSize: "medium",
    type: "procurement",
    title: "Stock 20 Indigenous-owned product lines across stores",
    targetYear: 2025,
    rapType: "innovate",
    history: [h("2023", "committed", 25), h("2024", "in_progress", 50), h("2025", "reported", 72)],
  }),
  mk({
    id: "cm-mapleretail-anti",
    orgName: "Maple Retail Co-op",
    sector: "retail",
    orgSize: "medium",
    type: "anti_racism",
    title: "Adopt and publish an anti-racism policy",
    targetYear: 2024,
    rapType: "reflect",
    history: [h("2023", "committed", 20), h("2024", "confirmed", 100)],
  }),
  mk({
    id: "cm-riverhealth-emp",
    orgName: "Riverstone Health",
    sector: "health",
    orgSize: "large",
    type: "employment",
    title: "Recruit Indigenous health workers to 5% of staff",
    targetYear: 2026,
    rapType: "stretch",
    history: [h("2024", "in_progress", 30), h("2025", "in_progress", 48)],
  }),
  mk({
    id: "cm-riverhealth-cul",
    orgName: "Riverstone Health",
    sector: "health",
    orgSize: "large",
    type: "cultural_learning",
    title: "Embed cultural safety into patient-care protocols",
    targetYear: 2025,
    rapType: "stretch",
    history: [h("2023", "committed", 15), h("2024", "in_progress", 45), h("2025", "reported", 78)],
  }),
  mk({
    id: "cm-citygov-gov",
    orgName: "City of Riverbend",
    sector: "government",
    orgSize: "enterprise",
    type: "governance",
    title: "Establish a standing Indigenous advisory council",
    targetYear: 2024,
    rapType: "innovate",
    history: [h("2023", "in_progress", 55), h("2024", "confirmed", 100)],
  }),
  mk({
    id: "cm-citygov-proc",
    orgName: "City of Riverbend",
    sector: "government",
    orgSize: "enterprise",
    type: "procurement",
    title: "5% set-aside for Indigenous suppliers in city contracts",
    targetYear: 2026,
    rapType: "innovate",
    history: [h("2024", "committed", 18), h("2025", "in_progress", 42)],
  }),
  mk({
    id: "cm-lakeshore-rel",
    orgName: "Lakeshore University",
    sector: "education",
    orgSize: "large",
    type: "relationships",
    title: "Partner with 4 First Nations student organizations",
    targetYear: 2025,
    rapType: "innovate",
    history: [h("2023", "in_progress", 40), h("2024", "reported", 70), h("2025", "confirmed", 100)],
  }),
  mk({
    id: "cm-lakeshore-cul",
    orgName: "Lakeshore University",
    sector: "education",
    orgSize: "large",
    type: "cultural_learning",
    title: "Fund 10 Indigenous education scholarships annually",
    targetYear: 2025,
    rapType: "innovate",
    history: [h("2023", "committed", 30), h("2024", "in_progress", 60), h("2025", "reported", 82)],
  }),
  mk({
    id: "cm-transitco-emp",
    orgName: "TransitCo",
    sector: "transport",
    orgSize: "medium",
    type: "employment",
    title: "Indigenous hiring target of 25 operations roles",
    targetYear: 2025,
    rapType: "reflect",
    history: [h("2023", "committed", 10), h("2024", "stalled", 18), h("2025", "stalled", 22)],
  }),
  mk({
    id: "cm-transitco-anti",
    orgName: "TransitCo",
    sector: "transport",
    orgSize: "medium",
    type: "anti_racism",
    title: "Train frontline staff on bias and de-escalation",
    targetYear: 2024,
    rapType: "reflect",
    history: [h("2023", "committed", 20), h("2024", "in_progress", 50)],
  }),
  mk({
    id: "cm-summit-proc",
    orgName: "Summit Advisory",
    sector: "consulting",
    orgSize: "small",
    type: "procurement",
    title: "Source catering and design from Indigenous businesses",
    targetYear: 2024,
    rapType: "reflect",
    history: [h("2023", "in_progress", 45), h("2024", "confirmed", 100)],
  }),
  mk({
    id: "cm-summit-gov",
    orgName: "Summit Advisory",
    sector: "consulting",
    orgSize: "small",
    type: "governance",
    title: "Appoint an internal RAP champion from leadership",
    targetYear: 2024,
    rapType: "reflect",
    history: [h("2023", "committed", 30), h("2024", "reported", 75)],
  }),
];
